services:

  # ---------- unit tests ----------

  test:
    build:
      context: .
      args:
        HOCON_JAR_URL: ${HOCON_JAR_URL:-}
    entrypoint: bash
    command: tests/run-tests

  # ---------- e2e targets ----------

  target1:
    build:
      context: .
      dockerfile: Dockerfile.server
    hostname: target1
    ports:
      - "2221:22"

  target2:
    build:
      context: .
      dockerfile: Dockerfile.server
    hostname: target2
    ports:
      - "2222:22"

  # ---------- e2e runner ----------

  e2e:
    build:
      context: .
      args:
        HOCON_JAR_URL: ${HOCON_JAR_URL:-}
    entrypoint: bash
    command: tests/e2e/run-e2e.sh
    environment:
      - TARGET1=target1
      - TARGET2=target2
    depends_on: [target1, target2]
